"""Add preferred locale to user

Revision ID: bb693ad2fbab
Revises: e1705947c729
Create Date: 2026-07-11 16:32:07.505617

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from ketos.utils import migration

# revision identifiers, used by Alembic.
revision: str = "bb693ad2fbab"
down_revision: str | None = "e1705947c729"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if not migration.column_exists(table_name="user", column_name="preferred_locale", conn=conn):
        with op.batch_alter_table("user", schema=None) as batch_op:
            batch_op.add_column(sa.Column("preferred_locale", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if migration.column_exists(table_name="user", column_name="preferred_locale", conn=conn):
        with op.batch_alter_table("user", schema=None) as batch_op:
            batch_op.drop_column("preferred_locale")

    # ### end Alembic commands ###
