// Syncthing device ids in their canonical form: eight dash-separated groups of
// seven base32 characters whose 14th, 28th, 42nd, and 56th characters are
// Luhn mod 32 check characters. The fixtures are real ids: four generated by
// the stand image's Syncthing 2.1.5 and the example id of the Syncthing
// documentation.
import { describe, expect, it } from 'vitest'
import { parseSyncthingDeviceId } from '../src/syncthing-device-id.ts'

/** Real device ids `syncthing device-id` printed for fresh homes. */
const REAL_IDS = [
  'WOMZ33X-WKQ2GXR-GJSDYTB-2JGCS6B-E63FEGC-K53B2SY-DZ74KXN-6T4TMAY',
  'RZU325K-XIIM65F-PXA6B7C-3E5RIMA-DPF6N7A-5WRKK6B-J5RMZHC-FMSNSA5',
  'QF33IZ4-UQMXKVM-564AW27-UUNOSES-75EXNCA-QK5JTLB-OZD4UNG-W5JFNAU',
  '6CTVASB-R7PNT7H-JUAQ2WS-MVX3UGO-OFLER7L-C6ZULGV-UESQTMA-OLZOFQE',
  'MFZWI3D-BONSGYC-YLTMRWG-C43ENR5-QXGZDMM-FZWI3DP-BONSGYY-LTMRWAD',
] as const

/**
 * Replace one character of the 56 data and check characters, counting from 0
 * and skipping dashes.
 * @param id - a canonical id.
 * @param index - position among the 56 non-dash characters.
 * @param replacement - the character to put there.
 * @returns the id with that character replaced.
 */
function replaceAt(id: string, index: number, replacement: string): string {
  const chars = id.replaceAll('-', '').split('')
  chars[index] = replacement
  const raw = chars.join('')
  return raw.match(/.{7}/gu)?.join('-') ?? raw
}

/**
 * A different base32 character at the same position.
 * @param char - the current character.
 * @returns another character of the alphabet.
 */
function other(char: string): string {
  return char === 'A' ? 'B' : 'A'
}

/** The base32 alphabet of device ids; a character's index is its 5-bit value. */
const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'

/**
 * The Luhn mod 32 check character of one 13-character data run, as the
 * Syncthing documentation describes it.
 * @param run - the data characters.
 * @returns the check character.
 */
function checkCharacter(run: string): string {
  let factor = 1
  let sum = 0
  for (const char of run) {
    const addend = factor * ALPHABET.indexOf(char)
    factor = factor === 1 ? 2 : 1
    sum += Math.floor(addend / 32) + (addend % 32)
  }
  return ALPHABET[(32 - (sum % 32)) % 32] as string
}

/**
 * The 32 bytes an id's 52 data characters encode; the four bits after the
 * 256th are dropped, as a base32 decoder that does not check padding does.
 * @param id - a dashed 56-character id.
 * @returns the decoded bytes.
 */
function decodedBytes(id: string): number[] {
  const raw = id.replaceAll('-', '')
  const data = [0, 1, 2, 3].map(group => raw.slice(group * 14, group * 14 + 13)).join('')
  const bits = data.split('').map(char => ALPHABET.indexOf(char).toString(2).padStart(5, '0')).join('')
  return (bits.slice(0, 256).match(/.{8}/gu) ?? []).map(byte => Number.parseInt(byte, 2))
}

/**
 * Every spelling of an id whose last data character keeps its data bit but
 * sets some of its four padding bits, with the check character recomputed.
 * @param id - a canonical id.
 * @returns the 15 non-canonical spellings.
 */
function paddedSpellings(id: string): string[] {
  const raw = id.replaceAll('-', '')
  const dataBit = ALPHABET.indexOf(raw[54] as string) & 0b10000
  return Array.from({ length: 15 }, (_, index) => {
    const run = `${raw.slice(42, 54)}${ALPHABET[dataBit | (index + 1)] as string}`
    const spelled = `${raw.slice(0, 42)}${run}${checkCharacter(run)}`
    return (spelled.match(/.{7}/gu) ?? []).join('-')
  })
}

describe('Syncthing device id', () => {
  it('accepts real ids in canonical form', () => {
    for (const id of REAL_IDS) expect(parseSyncthingDeviceId(id)).toBe(id)
  })

  it('refuses a wrong check character in every group', () => {
    for (const id of REAL_IDS) {
      for (const index of [13, 27, 41, 55]) {
        const raw = id.replaceAll('-', '')
        expect(parseSyncthingDeviceId(replaceAt(id, index, other(raw[index] as string)))).toBeUndefined()
      }
    }
  })

  it('refuses a changed data character, which no longer matches its check character', () => {
    const [id] = REAL_IDS
    const raw = id.replaceAll('-', '')
    for (const index of [0, 6, 12, 14, 30, 54]) {
      expect(parseSyncthingDeviceId(replaceAt(id, index, other(raw[index] as string)))).toBeUndefined()
    }
  })

  it('refuses the spellings whose padding bits are set, which decode to the same bytes as the canonical id', () => {
    expect(parseSyncthingDeviceId('WOMZ33X-WKQ2GXR-GJSDYTB-2JGCS6B-E63FEGC-K53B2SY-DZ74KXN-6T4TMBX')).toBeUndefined()
    for (const id of REAL_IDS) {
      const spellings = paddedSpellings(id)
      expect(new Set(spellings).size).toBe(15)
      for (const spelled of spellings) {
        expect(spelled).not.toBe(id)
        expect(decodedBytes(spelled)).toEqual(decodedBytes(id))
        expect(parseSyncthingDeviceId(spelled), spelled).toBeUndefined()
      }
    }
    expect(paddedSpellings(REAL_IDS[0])).toContain('WOMZ33X-WKQ2GXR-GJSDYTB-2JGCS6B-E63FEGC-K53B2SY-DZ74KXN-6T4TMBX')
  })

  it('refuses the wrong length', () => {
    const [id] = REAL_IDS
    expect(parseSyncthingDeviceId(id.slice(0, -1))).toBeUndefined()
    expect(parseSyncthingDeviceId(`${id}-AAAAAAA`)).toBeUndefined()
    expect(parseSyncthingDeviceId('')).toBeUndefined()
  })

  it('refuses characters outside the base32 alphabet, including the 0/1/8 typos Syncthing itself repairs', () => {
    const [id] = REAL_IDS
    for (const typo of ['0', '1', '8', '9', '=', ' ']) expect(parseSyncthingDeviceId(replaceAt(id, 3, typo))).toBeUndefined()
  })

  it('refuses lowercase, the dashless 56-character form, and the 52-character form without check characters', () => {
    const [id] = REAL_IDS
    expect(parseSyncthingDeviceId(id.toLowerCase())).toBeUndefined()
    expect(parseSyncthingDeviceId(id.replaceAll('-', ''))).toBeUndefined()
    const raw = id.replaceAll('-', '')
    const withoutChecks = [0, 1, 2, 3].map(group => raw.slice(group * 14, group * 14 + 13)).join('')
    expect(withoutChecks).toHaveLength(52)
    expect(parseSyncthingDeviceId(withoutChecks)).toBeUndefined()
  })

  it('refuses misplaced dashes and values that are not strings', () => {
    const [id] = REAL_IDS
    const raw = id.replaceAll('-', '')
    const shifted = `${raw.slice(0, 8)}-${raw.slice(8, 14)}-${raw.slice(14).match(/.{7}/gu)?.join('-') ?? ''}`
    expect(shifted).toHaveLength(63)
    expect(parseSyncthingDeviceId(shifted)).toBeUndefined()
    expect(parseSyncthingDeviceId(undefined)).toBeUndefined()
    expect(parseSyncthingDeviceId(42)).toBeUndefined()
    expect(parseSyncthingDeviceId({ deviceId: id })).toBeUndefined()
  })
})
